<?php

namespace Rene\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * Extrañamente este lo creo en Rene\BlogBundle\Entity y no en la ruta que 
 * esperaba que era  // src/Blogger/BlogBundle/Repository/BlogRepository.php. 
 * Asi que no se si esto va a funcionar, por las dudas hay que redireccionar todo
 * a esta ruta.
 */
class BlogRepository extends EntityRepository
{
    public function getLatestBlogs($limit = null)
    {
        $qb = $this->createQueryBuilder('b')
                   ->select('b')
                   ->addOrderBy('b.created', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
}
