ReneBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: ReneBlogBundle:Page:index }
    requirements:
        _method:  GET
        
ReneBlogBundle_about:
    pattern:  /about
    defaults: { _controller: ReneBlogBundle:Page:about }
    requirements:
        _method:  GET
      
ReneBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: ReneBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

ReneBlogBundle_blog_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: ReneBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+      
      
ReneBlogBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: ReneBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+
        
        
        