parameters:
#    rene_blog.example.class: Rene\BlogBundle\Example

services:
#    rene_blog.example:
#        class: %rene_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
 rene_blog.twig.extension:
        class: Rene\BlogBundle\Twig\Extensions\ReneBlogExtension
        tags:
            - { name: twig.extension }
